ALTER TABLE device ADD shop_id INT DEFAULT NULL AFTER `device_group_id`;
ALTER TABLE device ADD CONSTRAINT FK_92FB68E4D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) ON DELETE CASCADE;
CREATE INDEX IDX_92FB68E4D16C4DD ON device (shop_id);
CREATE INDEX name_idx ON shop (name);
