CREATE TABLE strategy (id VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, params LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', comment VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE device DROP version;
CREATE INDEX sn_idx ON device (sn);
ALTER TABLE campaign ADD strategy_id VARCHAR(32) DEFAULT NULL AFTER name;
ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DDD5CAD932 FOREIGN KEY (strategy_id) REFERENCES strategy (id);
CREATE INDEX IDX_1F1512DDD5CAD932 ON campaign (strategy_id);
