version: "3"

services:

  cms2.pixatori.com:
    container_name: cms2.pixatori.com
    restart: always
    build:
      context: .
    links:
      - mailer
      - redis1
    external_links:
      - database
    expose:
      - 80
      - 443
      - 6379

    ports:
      - "5000:80"

    volumes:
      - ../web:/var/www
      - ../web/www:/var/www/html
      - ../web/log/apache:/var/log/apache2
      - ./database/:/docker-entrypoint-initdb.d
    hostname:
      local.cz
    environment:
      VIRTUAL_HOST: cms2pixatori.local.cz
      VIRTUAL_NETWORK: nginx-proxy
      LETSENCRYPT_HOST: local.cz
      LETSENCRYPT_EMAIL: info@local.cz
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: b4RO2OT!}e
      MYSQL_DATABASE: cms2pixatori
      MYSQL_USER: cms2pixatori
      MYSQL_PASSWORD: aI#UzlQ49Jw91B
      COMPOSER_INTERACTION: "yes"


  mailer:
    image: nicescale/sendmail
    ports:
      - "25"
    environment:
      MAIL_DOMAIN: local.cz
      DP_USER: info@local.cz
      DP_PASS: b4RO2OT!}e

  redis1:
    image: 'bitnami/redis:latest'
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


networks:
  default:
    external:
      name: nginx-proxy