<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<style>
	#error-body { background: white; width: 500px; margin: 70px auto; padding: 10px 20px }
	#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
	#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
	#error-body small { font-size: 70%; color: gray }
</style>

<link href="../../bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../../css/style.css" rel="stylesheet">
<link href="../../css/colors/blue.css" id="theme"  rel="stylesheet">

<section id="wrapper" class="error-page">
    <div class="error-box">
        <div class="error-body text-center">
            <h1>500</h1>
            <h3 class="text-uppercase">Internal Server Error.</h3>
            <p class="text-muted m-t-30 m-b-30">Please try after some time</p>
<!--            <a href="/" class="btn btn-info btn-rounded waves-effect waves-light m-b-40">Back to home</a> </div>-->
        <footer class="footer text-center">2019 © Pixel Admin.</footer>
    </div>
</section>
